name: Build

on:
  push:
    branches: 
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build with AHK v2
        uses: nukdokplex/autohotkey-build@v0.1
        with:
          version: v2.0.2
          x64: true
          x86: true
          compression: upx
          in: ""
          out: build
      - name: Do domething with builded scripts
        shell: pwsh
        run: |
          ls build
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .\build\AHK2Manager_x64.exe
            .\build\AHK2Manager_x86.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}